services:
  server:
    build: ./server
    ports: 
      - "3001:3001"
    networks:
      - default
      - postgres
  client:
    build: ./client
    ports: 
      - "3000:3000"
    depends_on:
      - server
    networks:
      - default
networks:
  default:
  postgres:
    name: postgres_default
    external: true
