services:
  server:
    build: ./server
    restart: always
    ports: 
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    build: ./client
    restart: always
    ports: 
      - "3000:3000"
    depends_on:
      - server
